# Resetting (or not) gradients to zero
A minimal example showing the effect of not resetting gradients to zero, from [this answer](https://discuss.pytorch.org/t/why-do-we-need-to-set-the-gradients-manually-to-zero-in-pytorch/4903/12) to the question "Why do we need to set the gradients to zero in pytorch?" on the pytorch forum.

---
tags: pytorch, tutorial, deep learning, gradients, automatic differentiation

In [1]:
import torch

x = torch.tensor([0.], requires_grad=True)

print('Not resetting gradients to zero:')
for _ in range(3):
    y = x.sin()
    y.backward()
    print(x.grad)
    
print('\nResetting gradients to zero:')
    
for t in range(3):
    if x.grad is not None:
        x.grad.data.zero_()
    y = x.sin() 
    y.backward()
    print(x.grad)

Not resetting gradients to zero:
tensor([1.])
tensor([2.])
tensor([3.])

Resetting gradients to zero:
tensor([1.])
tensor([1.])
tensor([1.])
